wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1645784925
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 16
      - 17
      4: 3.8.5
      5: 0.12.10
      8:
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0001
